
services:
  fastapi:
    container_name: fastapi
    ports:
      - "8000:8000"
    build:
      dockerfile: Dockerfile
      network: host
    command: poetry run fastapi run src/crypto_tracker_api/main.py --host 0.0.0.0 --port 8000