
services:
  fastapi:
    container_name: fastapi
    ports:
      - "8000:8000"
    build:
      dockerfile: Dockerfile
    volumes:
      - "./src:/app/src"
    command: poetry run python -m uvicorn crypto_tracker_api.main:app --reload --host="0.0.0.0" --port="8000"